@startuml
'https://plantuml.com/class-diagram

class App {
void main()
ArrayList<Animal> getAnimals()
}
class Animal {
private name
private count
String getName()
int getCount()
}

class AnimalComparator {
public int compare()
}

App o-> Animal
App o-> AnimalComparator

@enduml